version: '3.8'

services:
  host:
    container_name: host-service
    image: 090188239653.dkr.ecr.ap-northeast-2.amazonaws.com/host-service
    volumes:
      - /home/ubuntu/config/host/application.yml:/config/host/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/host/application.yml
    ports:
      - "8083:8083"
    env_file:
      - /home/ubuntu/env/.env.host
    networks:
      - backend

networks:
  backend:
    external: true